/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-04-16 11:45:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/bootstrap.min.css\"/> \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/owl.carousel.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/animate.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/js/jquery-3.2.1.min.js\"/>\r\n");
      out.write("    <script src=\"https://unpkg.com/@popperjs/core@2/dist/umd/popper.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("     <!-- Page Preloder -->\r\n");
      out.write("\t<div id=\"preloder\">\r\n");
      out.write("\t\t<div class=\"loader\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("    <!-- Header Section-->\r\n");
      out.write("    <header class=\"header-section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <!-- logo -->\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <a class=\"site-logo\" href=\"index.jsp\">\r\n");
      out.write("                    <img id=\"logo_yellow\" src=\"resources/images/logo_yellow.svg\" alt=\"\">\r\n");
      out.write("                </a>    \r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"user-panel\">\r\n");
      out.write("\t\t\t\t<a href=\"views/mypage/mpMember/mpLogin.jsp\" style=\"text-decoration: none;\">Login / Register</a> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- responsive -->\r\n");
      out.write("\t\t\t<div class=\"nav-switch\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-bars\"></i>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- site menu -->\r\n");
      out.write("\t\t\t<nav class=\"main-menu\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">테마</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">지점소개</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">게시판</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">예약</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- 헤더 끝 -->\r\n");
      out.write("\r\n");
      out.write("    \t<!-- Latest news section -->\r\n");
      out.write("\t<div class=\"latest-news-section\">\r\n");
      out.write("\t\t<div class=\"ln-title\">Latest News</div>\r\n");
      out.write("\t\t<div class=\"news-ticker\">\r\n");
      out.write("\t\t\t<div class=\"news-ticker-contant\">\r\n");
      out.write("\t\t\t\t<div class=\"nt-item\"><span class=\"new\">new</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </div>\r\n");
      out.write("\t\t\t\t<div class=\"nt-item\"><span class=\"strategy\">strategy</span>Isum dolor sit amet, consectetur adipiscing elit. </div>\r\n");
      out.write("\t\t\t\t<div class=\"nt-item\"><span class=\"racing\">racing</span>Isum dolor sit amet, consectetur adipiscing elit. </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Latest news section end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- 메인 섹션 -->\r\n");
      out.write("    <section class=\"main-section\">\r\n");
      out.write("        <div class=\"container\"> \r\n");
      out.write("           <div class=\"middle\">\r\n");
      out.write("                <table>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <div class=\"mainlogo\" align=\"center\">\r\n");
      out.write("                            <img id=\"logoMain\" src=\"resources/images/logo_shadow.svg\" onmouseover=\"this.src='resources/images/logoShadowHover.svg'\" onmouseout=\"this.src='resources/images/logo_shadow.svg'\">\r\n");
      out.write("                            <p><button type=\"button\" class=\"res btn btn-outline-light\" style=\"opacity: 1;\">예약하기</button>\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <br clear=\"both\">\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    \r\n");
      out.write("                </table>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--  -->\r\n");
      out.write("\r\n");
      out.write("    <!-- 메인2 -->\r\n");
      out.write("    \r\n");
      out.write("    <section class=\"main_propos\">\r\n");
      out.write("        <br clear=\"both\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"middle parShowing show\" >\r\n");
      out.write("                <div class=\"tit_top\" >\r\n");
      out.write("                   <br><br>\r\n");
      out.write("                    <div class=\"feature_desc\">\r\n");
      out.write("                        각기 다른 테마의 방안에 갇힌 참가자가 되어 숨겨진 단서를 통해 <br>\r\n");
      out.write("\t\t\t\t\t\t<span>60분의 시간안에 공간을 탈출</span>하는 체험중심의 신개념 놀이문화 입니다.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"tit_bottom\" align=\"center\">\r\n");
      out.write("                    <h1 class=\"feature_title\" >전국 <span>55개 지점</span> 및 <span>60여개</span> 테마</h1>\r\n");
      out.write("                    <br><br>\r\n");
      out.write("                    <div class=\"feature_desc\">\r\n");
      out.write("                        <span>저희의 목적은 더욱 많은 분들에게 일상에서 느낄 수 없는 색다른 경험과<br>\r\n");
      out.write("                        한번도 겪어본적 없는 종류의 즐거움을 제공하는 것입니다.</span><br><br>\r\n");
      out.write("                        실화를 바탕으로한 살아있는 디테일과,<br>\r\n");
      out.write("                        다양한 장치들로 이루어진 체계적인 문제해결 시스템은 <br>\r\n");
      out.write("                        저희의 모토와 목적 실현의 단단한 기반입니다. <br><br>\r\n");
      out.write("\t\t\t\t\t\t저희는 특허중인 새로운 기술, 참신한 아이디어를 통해 다양한 연령층, 소비자를 만족시킬 수 있는<br>\r\n");
      out.write("체험 문화를 선도해 가고 있습니다.<br><br>\r\n");
      out.write("새로운 경험을 원하는 당신! 저희가 이루어드리겠습니다.\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 미들 3 -->\r\n");
      out.write("    <section class=\"main_guide\">\r\n");
      out.write("        <div class=\"conteiner\">\r\n");
      out.write("            <div class=\"middle\" align=\"center\">\r\n");
      out.write("                <h2 class=\"feature_title\">Beginners Guide</h2>\r\n");
      out.write("                <div class=\"row feature_desc\">\r\n");
      out.write("                    <div class=\"col s4 parShowing show\" style=\"transform: matrix(1,0,0,1,0,0); opacity:1;\">\r\n");
      out.write("                        <img src=\"resources/images/guide_01.png\" alt=\"\">\r\n");
      out.write("                        <p>\"당신은 탐정이 되었습니다.\" <br>\r\n");
      out.write("                            \"제한된 시간안에 추리하고 범인을 잡으세요.\"\r\n");
      out.write("                        </p>   \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col s4 parShowing show\" style=\"transform: matrix(1,0,0,1,0,0); opacity:1;\">\r\n");
      out.write("                        <img src=\"resources/images/guide_02.png\" alt=\"\">\r\n");
      out.write("                        <p>\"협동하고 빠르게 움직이십시오\" <br>\r\n");
      out.write("                            \"역할을 분담하고 다양한 관점에서 도전하십시오/\"\r\n");
      out.write("                        </p>   \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col s4 parShowing show\" style=\"transform: matrix(1,0,0,1,0,0); opacity:1;\">\r\n");
      out.write("                        <img src=\"resources/images/guide_03.png\" alt=\"\">\r\n");
      out.write("                        <p>\"출생의 비밀, 반전, 범죄의 사연등을 캐치하고\" <br>\r\n");
      out.write("                            \"탈출하시면서 한편의 영화속을 느끼실 겁니다.\"\r\n");
      out.write("                        </p>   \r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- Footer section -->\r\n");
      out.write("      <section class=\"footer-section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"footerTop\">\r\n");
      out.write("                <div class=\"footerTop_1\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"\">개인정보취급방침</a></li> &nbsp; | &nbsp;  \r\n");
      out.write("                        <li><a href=\"\">이용약관</a></li> &nbsp; | &nbsp;  \r\n");
      out.write("                        <li><a href=\"\">지점소개</a></li> &nbsp; | &nbsp;  \r\n");
      out.write("                        <li><a href=\"\">프랜차이즈 가맹문의</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"ftTop\">\r\n");
      out.write("                    <a href=\"\">BACK TO TOP</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"footer-bottom\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"ftlogo\">\r\n");
      out.write("                    <img src=\"resources/images/logo_yellow.svg\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"info\">\r\n");
      out.write("                 <p>\r\n");
      out.write("                        상호명 KH 주소 서울특별시 강남구 테헤란로14길 6 <br>\r\n");
      out.write("                        (주)RoomEscape 사업자등록번호 123-45-67890 <br>\r\n");
      out.write("                        대표전화 1800.0000 / Emai roomEscape@naver.com <br>\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--====== Javascripts & Jquery ======-->\r\n");
      out.write("\t<script src=\"resources/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/js/jquery.marquee.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
